version: "3"
services:

  app:
    depends_on:
     - mongo
    container_name: dockerize-node-mongo-app
    restart: always
    build: .
    env_file:
      - .env
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - HOST=$HOST
      - PORT=$PORT
    #map from image port (3000) to actual container port
    ports:
      - "8080:$PORT"
    links:
      - mongo

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: test-user
      MONGO_INITDB_ROOT_PASSWORD: test-password
      MONGO_INITDB_DATABASE: test-db
    ports:
    - "$DB_PORT:$DB_PORT"
    volumes:
      - mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro