version: "3"
services:
  app:
    container_name: dockerize-node-mongo-app
    restart: always
    build: .
    #map from image port (3000) to actual container port
    ports:
      - "8080:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    environment:
      #have to match config.js file
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

    #an example for mapping mongo port
    ports:
      - "27017:27017"