version: "2.1"
services:

  app:
    depends_on:
      mongo:
        condition: service_healthy
    container_name: dockerize-node-mongo-app
    restart: always
    build: .
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
      - API_KEY=$API_KEY
    #map from image port (3000) to actual container port
    ports:
      - "8080:3000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    env_file:
      - .env
    environment:
      #have to match config.js file
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
      MONGO_INITDB_DATABASE: first_db
    healthcheck:
      test: ["CMD", "echo", "show dbs", "|", "mongo"]
      interval: 30s
      timeout: 10s
      retries: 3