version: "3"
services:
  app:
    container_name: dockerize-node-mongo-app
    rastart: always
    build: .
    #map from image port (3000) to actual container port
    ports:
      - "8080:3000"
    links:
      - mongo
    mongo:
      container_name: mongo
      image: mongo
      ports:
        - "27018:27017"