version: "3"
services:

  app:
    depends_on:
     - mongo
    container_name: dockerize-node-mongo-app
    restart: always
    build: .
    env_file:
      - .env
    environment:
      - API_KEY=$API_KEY
    #map from image port (3000) to actual container port
    ports:
      - "8080:3000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27018"